// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Card struct {
	ID              uuid.UUID
	Language1       string
	Language2       string
	DeskID          uuid.UUID
	ImportanceValue int32
}

type Desk struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ImageLink   sql.NullString
	Title       string
	Description string
}

type Progress struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	CardID        uuid.UUID
	ProgressLevel int32
	Date          time.Time
}

type Todo struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Todo        string
	IsTrue      sql.NullBool
	Description string
}

type User struct {
	ID         uuid.UUID
	Name       string
	Surname    string
	Username   string
	Email      string
	Password   string
	IsVerified sql.NullBool
}

type UserDeskCardCount struct {
	UserID    uuid.UUID
	UserName  string
	DeskCount int64
	CardCount int64
}

type VerificationCode struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	Code      string
	CreatedAt sql.NullTime
	ExpiresAt sql.NullTime
}
