// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createCard = `-- name: CreateCard :exec
INSERT INTO card (language_1, language_2, description, desk_id) VALUES ($1, $2, $3, $4)
`

type CreateCardParams struct {
	Language1   string
	Language2   string
	Description string
	DeskID      int32
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) error {
	_, err := q.db.ExecContext(ctx, createCard,
		arg.Language1,
		arg.Language2,
		arg.Description,
		arg.DeskID,
	)
	return err
}

const createDesk = `-- name: CreateDesk :exec
INSERT INTO desk (title, description, user_id) VALUES ($1, $2, $3)
`

type CreateDeskParams struct {
	Title       string
	Description string
	UserID      int32
}

func (q *Queries) CreateDesk(ctx context.Context, arg CreateDeskParams) error {
	_, err := q.db.ExecContext(ctx, createDesk, arg.Title, arg.Description, arg.UserID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, surname, username, email, password) 
VALUES ($1, $2, $3, $4, $5) 
RETURNING id
`

type CreateUserParams struct {
	Name     string
	Surname  string
	Username string
	Email    string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Surname,
		arg.Username,
		arg.Email,
		arg.Password,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM card WHERE id = $1
`

func (q *Queries) DeleteCard(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCard, id)
	return err
}

const deleteDesk = `-- name: DeleteDesk :exec
DELETE FROM desk WHERE id = $1
`

func (q *Queries) DeleteDesk(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteDesk, id)
	return err
}

const getCardById = `-- name: GetCardById :one
SELECT id, language_1, language_2, description, desk_id FROM card WHERE id = $1
`

type GetCardByIdRow struct {
	ID          int32
	Language1   string
	Language2   string
	Description string
	DeskID      int32
}

// Card-related queries
func (q *Queries) GetCardById(ctx context.Context, id int32) (GetCardByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getCardById, id)
	var i GetCardByIdRow
	err := row.Scan(
		&i.ID,
		&i.Language1,
		&i.Language2,
		&i.Description,
		&i.DeskID,
	)
	return i, err
}

const getCardsByDeskId = `-- name: GetCardsByDeskId :many
SELECT id, language_1, language_2, description, desk_id FROM card WHERE desk_id = $1
`

type GetCardsByDeskIdRow struct {
	ID          int32
	Language1   string
	Language2   string
	Description string
	DeskID      int32
}

func (q *Queries) GetCardsByDeskId(ctx context.Context, deskID int32) ([]GetCardsByDeskIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getCardsByDeskId, deskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCardsByDeskIdRow
	for rows.Next() {
		var i GetCardsByDeskIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Language1,
			&i.Language2,
			&i.Description,
			&i.DeskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeskById = `-- name: GetDeskById :one
SELECT id, title, description, user_id FROM desk WHERE id = $1
`

type GetDeskByIdRow struct {
	ID          int32
	Title       string
	Description string
	UserID      int32
}

func (q *Queries) GetDeskById(ctx context.Context, id int32) (GetDeskByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getDeskById, id)
	var i GetDeskByIdRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.UserID,
	)
	return i, err
}

const getDesksByUserId = `-- name: GetDesksByUserId :many
SELECT id, title, description, user_id FROM desk WHERE user_id = $1
`

type GetDesksByUserIdRow struct {
	ID          int32
	Title       string
	Description string
	UserID      int32
}

func (q *Queries) GetDesksByUserId(ctx context.Context, userID int32) ([]GetDesksByUserIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getDesksByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDesksByUserIdRow
	for rows.Next() {
		var i GetDesksByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHashPass = `-- name: GetHashPass :one
SELECT password 
FROM users 
WHERE email = $1
`

func (q *Queries) GetHashPass(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, getHashPass, email)
	var password string
	err := row.Scan(&password)
	return password, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, surname, username, email, is_verified FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID         int32
	Name       string
	Surname    string
	Username   string
	Email      string
	IsVerified sql.NullBool
}

// User-related queries
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Username,
		&i.Email,
		&i.IsVerified,
	)
	return i, err
}

const isUserVerified = `-- name: IsUserVerified :one
SELECT is_verified, email FROM users WHERE id = $1
`

type IsUserVerifiedRow struct {
	IsVerified sql.NullBool
	Email      string
}

func (q *Queries) IsUserVerified(ctx context.Context, id int32) (IsUserVerifiedRow, error) {
	row := q.db.QueryRowContext(ctx, isUserVerified, id)
	var i IsUserVerifiedRow
	err := row.Scan(&i.IsVerified, &i.Email)
	return i, err
}

const updateCard = `-- name: UpdateCard :exec
UPDATE card SET language_1 = $1, language_2 = $2, description = $3 WHERE id = $4
`

type UpdateCardParams struct {
	Language1   string
	Language2   string
	Description string
	ID          int32
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) error {
	_, err := q.db.ExecContext(ctx, updateCard,
		arg.Language1,
		arg.Language2,
		arg.Description,
		arg.ID,
	)
	return err
}

const updateDesk = `-- name: UpdateDesk :exec
UPDATE desk SET title = $1, description = $2 WHERE id = $3
`

type UpdateDeskParams struct {
	Title       string
	Description string
	ID          int32
}

func (q *Queries) UpdateDesk(ctx context.Context, arg UpdateDeskParams) error {
	_, err := q.db.ExecContext(ctx, updateDesk, arg.Title, arg.Description, arg.ID)
	return err
}

const updateUserInfo = `-- name: UpdateUserInfo :exec
UPDATE users SET name = $1, email = $2 WHERE id = $3
`

type UpdateUserInfoParams struct {
	Name  string
	Email string
	ID    int32
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) error {
	_, err := q.db.ExecContext(ctx, updateUserInfo, arg.Name, arg.Email, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password = $1 WHERE email = $2
`

type UpdateUserPasswordParams struct {
	Password string
	Email    string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.Password, arg.Email)
	return err
}

const verificationCodeCreate = `-- name: VerificationCodeCreate :one
INSERT INTO verification_codes (user_id, code, created_at, expires_at)
VALUES ($1, $2, NOW(), NOW() + INTERVAL '1 day')
RETURNING id
`

type VerificationCodeCreateParams struct {
	UserID sql.NullInt32
	Code   string
}

func (q *Queries) VerificationCodeCreate(ctx context.Context, arg VerificationCodeCreateParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, verificationCodeCreate, arg.UserID, arg.Code)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const verifyUser = `-- name: VerifyUser :exec
WITH delete_verification AS (
  DELETE FROM verification_codes
  WHERE user_id = $1
    AND code = $3
    AND expires_at > NOW()
  RETURNING user_id
)
UPDATE users
SET is_verified = TRUE
WHERE users.id = $1 -- users tablosunun id'si
  AND users.email = $2 -- users tablosunun email'i
  AND EXISTS (SELECT 1 FROM delete_verification)
`

type VerifyUserParams struct {
	ID    int32
	Email string
	Code  string
}

func (q *Queries) VerifyUser(ctx context.Context, arg VerifyUserParams) error {
	_, err := q.db.ExecContext(ctx, verifyUser, arg.ID, arg.Email, arg.Code)
	return err
}
